"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBaseEscrow__factory = exports.EscrowSrc__factory = exports.EscrowFactory__factory = exports.EscrowDst__factory = exports.Escrow__factory = exports.BaseEscrowFactory__factory = exports.BaseEscrow__factory = exports.MockTRX__factory = exports.DemoResolverV2__factory = exports.DemoResolver__factory = exports.Strings__factory = exports.ShortStrings__factory = exports.ReentrancyGuard__factory = exports.Pausable__factory = exports.Nonces__factory = exports.SafeCast__factory = exports.IERC165__factory = exports.Errors__factory = exports.MerkleProof__factory = exports.EIP712__factory = exports.ECDSA__factory = exports.Create2__factory = exports.IERC721__factory = exports.IERC20__factory = exports.IERC20Permit__factory = exports.IERC20Metadata__factory = exports.ERC20Permit__factory = exports.ERC20__factory = exports.IERC1155__factory = exports.Clones__factory = exports.IERC5267__factory = exports.IERC1271__factory = exports.IERC721Errors__factory = exports.IERC20Errors__factory = exports.IERC1155Errors__factory = exports.Ownable__factory = exports.AggregatorV3Interface__factory = exports.AggregatorV2V3Interface__factory = exports.AggregatorInterface__factory = exports.PermitAndCall__factory = exports.OnlyWethReceiver__factory = exports.EthReceiver__factory = exports.UniERC20__factory = exports.SafeERC20__factory = exports.IWETH__factory = exports.IPermit2__factory = exports.IERC7597Permit__factory = exports.IERC20MetadataUppercase__factory = exports.IDaiLikePermit__factory = exports.factories = void 0;
exports.ExtensionMock__factory = exports.CallsSimulator__factory = exports.ArbitraryPredicateMock__factory = exports.AggregatorMock__factory = exports.LimitOrderProtocol__factory = exports.RemainingInvalidatorLib__factory = exports.OffsetsLib__factory = exports.BitInvalidatorLib__factory = exports.ITakerInteraction__factory = exports.IPreInteraction__factory = exports.IPostInteraction__factory = exports.IPermit2WitnessTransferFrom__factory = exports.IOrderRegistrator__factory = exports.ICreate3Deployer__factory = exports.IAmountGetter__factory = exports.SeriesNonceManager__factory = exports.SeriesEpochManager__factory = exports.PredicateHelper__factory = exports.OrderRegistrator__factory = exports.RangeAmountCalculator__factory = exports.PriorityFeeLimiter__factory = exports.Permit2WitnessProxy__factory = exports.OrderIdInvalidator__factory = exports.ImmutableOwner__factory = exports.FeeTaker__factory = exports.ETHOrders__factory = exports.ERC721ProxySafe__factory = exports.ERC721Proxy__factory = exports.ERC1155Proxy__factory = exports.DutchAuctionCalculator__factory = exports.ChainlinkCalculator__factory = exports.ApprovalPreInteraction__factory = exports.AmountGetterWithFee__factory = exports.AmountGetterBase__factory = exports.MinimalProxyZkSync__factory = exports.EscrowZkSync__factory = exports.EscrowSrcZkSync__factory = exports.EscrowFactoryZkSync__factory = exports.EscrowDstZkSync__factory = exports.ResolverExample__factory = exports.NoReceiveCaller__factory = exports.ERC20True__factory = exports.MerkleStorageInvalidator__factory = exports.IResolverExample__factory = exports.IOrderMixin__factory = exports.IMerkleStorageInvalidator__factory = exports.IEscrowSrc__factory = exports.IEscrowFactory__factory = exports.IEscrowDst__factory = exports.IEscrow__factory = void 0;
exports.TronEscrowSrc__factory = exports.TronEscrowFactoryPatched__factory = exports.TronEscrowDst__factory = exports.TronCreate2Test__factory = exports.TronClonesTest__factory = exports.SimpleImplementation__factory = exports.AddressLibTest__factory = exports.ITronEscrow__factory = exports.TronFusionExtension__factory = exports.ResolverValidationExtension__factory = exports.BaseExtension__factory = exports.Resolver__factory = exports.OrderMixin__factory = exports.OrderLib__factory = exports.WrappedTokenMock__factory = exports.TakerContract__factory = exports.RecursiveMatcher__factory = exports.MakerContract__factory = exports.InteractionMock__factory = exports.HashChecker__factory = void 0;
exports.factories = __importStar(require("./factories"));
var IDaiLikePermit__factory_1 = require("./factories/@1inch/solidity-utils/contracts/interfaces/IDaiLikePermit__factory");
Object.defineProperty(exports, "IDaiLikePermit__factory", { enumerable: true, get: function () { return IDaiLikePermit__factory_1.IDaiLikePermit__factory; } });
var IERC20MetadataUppercase__factory_1 = require("./factories/@1inch/solidity-utils/contracts/interfaces/IERC20MetadataUppercase__factory");
Object.defineProperty(exports, "IERC20MetadataUppercase__factory", { enumerable: true, get: function () { return IERC20MetadataUppercase__factory_1.IERC20MetadataUppercase__factory; } });
var IERC7597Permit__factory_1 = require("./factories/@1inch/solidity-utils/contracts/interfaces/IERC7597Permit__factory");
Object.defineProperty(exports, "IERC7597Permit__factory", { enumerable: true, get: function () { return IERC7597Permit__factory_1.IERC7597Permit__factory; } });
var IPermit2__factory_1 = require("./factories/@1inch/solidity-utils/contracts/interfaces/IPermit2__factory");
Object.defineProperty(exports, "IPermit2__factory", { enumerable: true, get: function () { return IPermit2__factory_1.IPermit2__factory; } });
var IWETH__factory_1 = require("./factories/@1inch/solidity-utils/contracts/interfaces/IWETH__factory");
Object.defineProperty(exports, "IWETH__factory", { enumerable: true, get: function () { return IWETH__factory_1.IWETH__factory; } });
var SafeERC20__factory_1 = require("./factories/@1inch/solidity-utils/contracts/libraries/SafeERC20__factory");
Object.defineProperty(exports, "SafeERC20__factory", { enumerable: true, get: function () { return SafeERC20__factory_1.SafeERC20__factory; } });
var UniERC20__factory_1 = require("./factories/@1inch/solidity-utils/contracts/libraries/UniERC20__factory");
Object.defineProperty(exports, "UniERC20__factory", { enumerable: true, get: function () { return UniERC20__factory_1.UniERC20__factory; } });
var EthReceiver__factory_1 = require("./factories/@1inch/solidity-utils/contracts/mixins/EthReceiver__factory");
Object.defineProperty(exports, "EthReceiver__factory", { enumerable: true, get: function () { return EthReceiver__factory_1.EthReceiver__factory; } });
var OnlyWethReceiver__factory_1 = require("./factories/@1inch/solidity-utils/contracts/mixins/OnlyWethReceiver__factory");
Object.defineProperty(exports, "OnlyWethReceiver__factory", { enumerable: true, get: function () { return OnlyWethReceiver__factory_1.OnlyWethReceiver__factory; } });
var PermitAndCall__factory_1 = require("./factories/@1inch/solidity-utils/contracts/mixins/PermitAndCall__factory");
Object.defineProperty(exports, "PermitAndCall__factory", { enumerable: true, get: function () { return PermitAndCall__factory_1.PermitAndCall__factory; } });
var AggregatorInterface__factory_1 = require("./factories/@chainlink/contracts/src/v0.8/interfaces/AggregatorInterface__factory");
Object.defineProperty(exports, "AggregatorInterface__factory", { enumerable: true, get: function () { return AggregatorInterface__factory_1.AggregatorInterface__factory; } });
var AggregatorV2V3Interface__factory_1 = require("./factories/@chainlink/contracts/src/v0.8/interfaces/AggregatorV2V3Interface__factory");
Object.defineProperty(exports, "AggregatorV2V3Interface__factory", { enumerable: true, get: function () { return AggregatorV2V3Interface__factory_1.AggregatorV2V3Interface__factory; } });
var AggregatorV3Interface__factory_1 = require("./factories/@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface__factory");
Object.defineProperty(exports, "AggregatorV3Interface__factory", { enumerable: true, get: function () { return AggregatorV3Interface__factory_1.AggregatorV3Interface__factory; } });
var Ownable__factory_1 = require("./factories/@openzeppelin/contracts/access/Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var IERC1155Errors__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC1155Errors__factory");
Object.defineProperty(exports, "IERC1155Errors__factory", { enumerable: true, get: function () { return IERC1155Errors__factory_1.IERC1155Errors__factory; } });
var IERC20Errors__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC20Errors__factory");
Object.defineProperty(exports, "IERC20Errors__factory", { enumerable: true, get: function () { return IERC20Errors__factory_1.IERC20Errors__factory; } });
var IERC721Errors__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC721Errors__factory");
Object.defineProperty(exports, "IERC721Errors__factory", { enumerable: true, get: function () { return IERC721Errors__factory_1.IERC721Errors__factory; } });
var IERC1271__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/IERC1271__factory");
Object.defineProperty(exports, "IERC1271__factory", { enumerable: true, get: function () { return IERC1271__factory_1.IERC1271__factory; } });
var IERC5267__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/IERC5267__factory");
Object.defineProperty(exports, "IERC5267__factory", { enumerable: true, get: function () { return IERC5267__factory_1.IERC5267__factory; } });
var Clones__factory_1 = require("./factories/@openzeppelin/contracts/proxy/Clones__factory");
Object.defineProperty(exports, "Clones__factory", { enumerable: true, get: function () { return Clones__factory_1.Clones__factory; } });
var IERC1155__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC1155/IERC1155__factory");
Object.defineProperty(exports, "IERC1155__factory", { enumerable: true, get: function () { return IERC1155__factory_1.IERC1155__factory; } });
var ERC20__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory");
Object.defineProperty(exports, "ERC20__factory", { enumerable: true, get: function () { return ERC20__factory_1.ERC20__factory; } });
var ERC20Permit__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit__factory");
Object.defineProperty(exports, "ERC20Permit__factory", { enumerable: true, get: function () { return ERC20Permit__factory_1.ERC20Permit__factory; } });
var IERC20Metadata__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory");
Object.defineProperty(exports, "IERC20Metadata__factory", { enumerable: true, get: function () { return IERC20Metadata__factory_1.IERC20Metadata__factory; } });
var IERC20Permit__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Permit__factory");
Object.defineProperty(exports, "IERC20Permit__factory", { enumerable: true, get: function () { return IERC20Permit__factory_1.IERC20Permit__factory; } });
var IERC20__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var IERC721__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC721/IERC721__factory");
Object.defineProperty(exports, "IERC721__factory", { enumerable: true, get: function () { return IERC721__factory_1.IERC721__factory; } });
var Create2__factory_1 = require("./factories/@openzeppelin/contracts/utils/Create2__factory");
Object.defineProperty(exports, "Create2__factory", { enumerable: true, get: function () { return Create2__factory_1.Create2__factory; } });
var ECDSA__factory_1 = require("./factories/@openzeppelin/contracts/utils/cryptography/ECDSA__factory");
Object.defineProperty(exports, "ECDSA__factory", { enumerable: true, get: function () { return ECDSA__factory_1.ECDSA__factory; } });
var EIP712__factory_1 = require("./factories/@openzeppelin/contracts/utils/cryptography/EIP712__factory");
Object.defineProperty(exports, "EIP712__factory", { enumerable: true, get: function () { return EIP712__factory_1.EIP712__factory; } });
var MerkleProof__factory_1 = require("./factories/@openzeppelin/contracts/utils/cryptography/MerkleProof__factory");
Object.defineProperty(exports, "MerkleProof__factory", { enumerable: true, get: function () { return MerkleProof__factory_1.MerkleProof__factory; } });
var Errors__factory_1 = require("./factories/@openzeppelin/contracts/utils/Errors__factory");
Object.defineProperty(exports, "Errors__factory", { enumerable: true, get: function () { return Errors__factory_1.Errors__factory; } });
var IERC165__factory_1 = require("./factories/@openzeppelin/contracts/utils/introspection/IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var SafeCast__factory_1 = require("./factories/@openzeppelin/contracts/utils/math/SafeCast__factory");
Object.defineProperty(exports, "SafeCast__factory", { enumerable: true, get: function () { return SafeCast__factory_1.SafeCast__factory; } });
var Nonces__factory_1 = require("./factories/@openzeppelin/contracts/utils/Nonces__factory");
Object.defineProperty(exports, "Nonces__factory", { enumerable: true, get: function () { return Nonces__factory_1.Nonces__factory; } });
var Pausable__factory_1 = require("./factories/@openzeppelin/contracts/utils/Pausable__factory");
Object.defineProperty(exports, "Pausable__factory", { enumerable: true, get: function () { return Pausable__factory_1.Pausable__factory; } });
var ReentrancyGuard__factory_1 = require("./factories/@openzeppelin/contracts/utils/ReentrancyGuard__factory");
Object.defineProperty(exports, "ReentrancyGuard__factory", { enumerable: true, get: function () { return ReentrancyGuard__factory_1.ReentrancyGuard__factory; } });
var ShortStrings__factory_1 = require("./factories/@openzeppelin/contracts/utils/ShortStrings__factory");
Object.defineProperty(exports, "ShortStrings__factory", { enumerable: true, get: function () { return ShortStrings__factory_1.ShortStrings__factory; } });
var Strings__factory_1 = require("./factories/@openzeppelin/contracts/utils/Strings__factory");
Object.defineProperty(exports, "Strings__factory", { enumerable: true, get: function () { return Strings__factory_1.Strings__factory; } });
var DemoResolver__factory_1 = require("./factories/contracts/ethereum/DemoResolver__factory");
Object.defineProperty(exports, "DemoResolver__factory", { enumerable: true, get: function () { return DemoResolver__factory_1.DemoResolver__factory; } });
var DemoResolverV2__factory_1 = require("./factories/contracts/ethereum/DemoResolverV2__factory");
Object.defineProperty(exports, "DemoResolverV2__factory", { enumerable: true, get: function () { return DemoResolverV2__factory_1.DemoResolverV2__factory; } });
var MockTRX__factory_1 = require("./factories/contracts/ethereum/MockTRX__factory");
Object.defineProperty(exports, "MockTRX__factory", { enumerable: true, get: function () { return MockTRX__factory_1.MockTRX__factory; } });
var BaseEscrow__factory_1 = require("./factories/contracts/ethereum/official-escrow/BaseEscrow__factory");
Object.defineProperty(exports, "BaseEscrow__factory", { enumerable: true, get: function () { return BaseEscrow__factory_1.BaseEscrow__factory; } });
var BaseEscrowFactory__factory_1 = require("./factories/contracts/ethereum/official-escrow/BaseEscrowFactory__factory");
Object.defineProperty(exports, "BaseEscrowFactory__factory", { enumerable: true, get: function () { return BaseEscrowFactory__factory_1.BaseEscrowFactory__factory; } });
var Escrow__factory_1 = require("./factories/contracts/ethereum/official-escrow/Escrow__factory");
Object.defineProperty(exports, "Escrow__factory", { enumerable: true, get: function () { return Escrow__factory_1.Escrow__factory; } });
var EscrowDst__factory_1 = require("./factories/contracts/ethereum/official-escrow/EscrowDst__factory");
Object.defineProperty(exports, "EscrowDst__factory", { enumerable: true, get: function () { return EscrowDst__factory_1.EscrowDst__factory; } });
var EscrowFactory__factory_1 = require("./factories/contracts/ethereum/official-escrow/EscrowFactory__factory");
Object.defineProperty(exports, "EscrowFactory__factory", { enumerable: true, get: function () { return EscrowFactory__factory_1.EscrowFactory__factory; } });
var EscrowSrc__factory_1 = require("./factories/contracts/ethereum/official-escrow/EscrowSrc__factory");
Object.defineProperty(exports, "EscrowSrc__factory", { enumerable: true, get: function () { return EscrowSrc__factory_1.EscrowSrc__factory; } });
var IBaseEscrow__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IBaseEscrow__factory");
Object.defineProperty(exports, "IBaseEscrow__factory", { enumerable: true, get: function () { return IBaseEscrow__factory_1.IBaseEscrow__factory; } });
var IEscrow__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IEscrow__factory");
Object.defineProperty(exports, "IEscrow__factory", { enumerable: true, get: function () { return IEscrow__factory_1.IEscrow__factory; } });
var IEscrowDst__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IEscrowDst__factory");
Object.defineProperty(exports, "IEscrowDst__factory", { enumerable: true, get: function () { return IEscrowDst__factory_1.IEscrowDst__factory; } });
var IEscrowFactory__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IEscrowFactory__factory");
Object.defineProperty(exports, "IEscrowFactory__factory", { enumerable: true, get: function () { return IEscrowFactory__factory_1.IEscrowFactory__factory; } });
var IEscrowSrc__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IEscrowSrc__factory");
Object.defineProperty(exports, "IEscrowSrc__factory", { enumerable: true, get: function () { return IEscrowSrc__factory_1.IEscrowSrc__factory; } });
var IMerkleStorageInvalidator__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IMerkleStorageInvalidator__factory");
Object.defineProperty(exports, "IMerkleStorageInvalidator__factory", { enumerable: true, get: function () { return IMerkleStorageInvalidator__factory_1.IMerkleStorageInvalidator__factory; } });
var IOrderMixin__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IOrderMixin__factory");
Object.defineProperty(exports, "IOrderMixin__factory", { enumerable: true, get: function () { return IOrderMixin__factory_1.IOrderMixin__factory; } });
var IResolverExample__factory_1 = require("./factories/contracts/ethereum/official-escrow/interfaces/IResolverExample__factory");
Object.defineProperty(exports, "IResolverExample__factory", { enumerable: true, get: function () { return IResolverExample__factory_1.IResolverExample__factory; } });
var MerkleStorageInvalidator__factory_1 = require("./factories/contracts/ethereum/official-escrow/MerkleStorageInvalidator__factory");
Object.defineProperty(exports, "MerkleStorageInvalidator__factory", { enumerable: true, get: function () { return MerkleStorageInvalidator__factory_1.MerkleStorageInvalidator__factory; } });
var ERC20True__factory_1 = require("./factories/contracts/ethereum/official-escrow/mocks/ERC20True__factory");
Object.defineProperty(exports, "ERC20True__factory", { enumerable: true, get: function () { return ERC20True__factory_1.ERC20True__factory; } });
var NoReceiveCaller__factory_1 = require("./factories/contracts/ethereum/official-escrow/mocks/NoReceiveCaller__factory");
Object.defineProperty(exports, "NoReceiveCaller__factory", { enumerable: true, get: function () { return NoReceiveCaller__factory_1.NoReceiveCaller__factory; } });
var ResolverExample__factory_1 = require("./factories/contracts/ethereum/official-escrow/mocks/ResolverExample__factory");
Object.defineProperty(exports, "ResolverExample__factory", { enumerable: true, get: function () { return ResolverExample__factory_1.ResolverExample__factory; } });
var EscrowDstZkSync__factory_1 = require("./factories/contracts/ethereum/official-escrow/zkSync/EscrowDstZkSync__factory");
Object.defineProperty(exports, "EscrowDstZkSync__factory", { enumerable: true, get: function () { return EscrowDstZkSync__factory_1.EscrowDstZkSync__factory; } });
var EscrowFactoryZkSync__factory_1 = require("./factories/contracts/ethereum/official-escrow/zkSync/EscrowFactoryZkSync__factory");
Object.defineProperty(exports, "EscrowFactoryZkSync__factory", { enumerable: true, get: function () { return EscrowFactoryZkSync__factory_1.EscrowFactoryZkSync__factory; } });
var EscrowSrcZkSync__factory_1 = require("./factories/contracts/ethereum/official-escrow/zkSync/EscrowSrcZkSync__factory");
Object.defineProperty(exports, "EscrowSrcZkSync__factory", { enumerable: true, get: function () { return EscrowSrcZkSync__factory_1.EscrowSrcZkSync__factory; } });
var EscrowZkSync__factory_1 = require("./factories/contracts/ethereum/official-escrow/zkSync/EscrowZkSync__factory");
Object.defineProperty(exports, "EscrowZkSync__factory", { enumerable: true, get: function () { return EscrowZkSync__factory_1.EscrowZkSync__factory; } });
var MinimalProxyZkSync__factory_1 = require("./factories/contracts/ethereum/official-escrow/zkSync/MinimalProxyZkSync__factory");
Object.defineProperty(exports, "MinimalProxyZkSync__factory", { enumerable: true, get: function () { return MinimalProxyZkSync__factory_1.MinimalProxyZkSync__factory; } });
var AmountGetterBase__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/AmountGetterBase__factory");
Object.defineProperty(exports, "AmountGetterBase__factory", { enumerable: true, get: function () { return AmountGetterBase__factory_1.AmountGetterBase__factory; } });
var AmountGetterWithFee__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/AmountGetterWithFee__factory");
Object.defineProperty(exports, "AmountGetterWithFee__factory", { enumerable: true, get: function () { return AmountGetterWithFee__factory_1.AmountGetterWithFee__factory; } });
var ApprovalPreInteraction__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ApprovalPreInteraction__factory");
Object.defineProperty(exports, "ApprovalPreInteraction__factory", { enumerable: true, get: function () { return ApprovalPreInteraction__factory_1.ApprovalPreInteraction__factory; } });
var ChainlinkCalculator__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ChainlinkCalculator__factory");
Object.defineProperty(exports, "ChainlinkCalculator__factory", { enumerable: true, get: function () { return ChainlinkCalculator__factory_1.ChainlinkCalculator__factory; } });
var DutchAuctionCalculator__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/DutchAuctionCalculator__factory");
Object.defineProperty(exports, "DutchAuctionCalculator__factory", { enumerable: true, get: function () { return DutchAuctionCalculator__factory_1.DutchAuctionCalculator__factory; } });
var ERC1155Proxy__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ERC1155Proxy__factory");
Object.defineProperty(exports, "ERC1155Proxy__factory", { enumerable: true, get: function () { return ERC1155Proxy__factory_1.ERC1155Proxy__factory; } });
var ERC721Proxy__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ERC721Proxy__factory");
Object.defineProperty(exports, "ERC721Proxy__factory", { enumerable: true, get: function () { return ERC721Proxy__factory_1.ERC721Proxy__factory; } });
var ERC721ProxySafe__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ERC721ProxySafe__factory");
Object.defineProperty(exports, "ERC721ProxySafe__factory", { enumerable: true, get: function () { return ERC721ProxySafe__factory_1.ERC721ProxySafe__factory; } });
var ETHOrders__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ETHOrders__factory");
Object.defineProperty(exports, "ETHOrders__factory", { enumerable: true, get: function () { return ETHOrders__factory_1.ETHOrders__factory; } });
var FeeTaker__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/FeeTaker__factory");
Object.defineProperty(exports, "FeeTaker__factory", { enumerable: true, get: function () { return FeeTaker__factory_1.FeeTaker__factory; } });
var ImmutableOwner__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/ImmutableOwner__factory");
Object.defineProperty(exports, "ImmutableOwner__factory", { enumerable: true, get: function () { return ImmutableOwner__factory_1.ImmutableOwner__factory; } });
var OrderIdInvalidator__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/OrderIdInvalidator__factory");
Object.defineProperty(exports, "OrderIdInvalidator__factory", { enumerable: true, get: function () { return OrderIdInvalidator__factory_1.OrderIdInvalidator__factory; } });
var Permit2WitnessProxy__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/Permit2WitnessProxy__factory");
Object.defineProperty(exports, "Permit2WitnessProxy__factory", { enumerable: true, get: function () { return Permit2WitnessProxy__factory_1.Permit2WitnessProxy__factory; } });
var PriorityFeeLimiter__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/PrioirityFeeLimiter.sol/PriorityFeeLimiter__factory");
Object.defineProperty(exports, "PriorityFeeLimiter__factory", { enumerable: true, get: function () { return PriorityFeeLimiter__factory_1.PriorityFeeLimiter__factory; } });
var RangeAmountCalculator__factory_1 = require("./factories/contracts/ethereum/official-lop/extensions/RangeAmountCalculator__factory");
Object.defineProperty(exports, "RangeAmountCalculator__factory", { enumerable: true, get: function () { return RangeAmountCalculator__factory_1.RangeAmountCalculator__factory; } });
var OrderRegistrator__factory_1 = require("./factories/contracts/ethereum/official-lop/helpers/OrderRegistrator__factory");
Object.defineProperty(exports, "OrderRegistrator__factory", { enumerable: true, get: function () { return OrderRegistrator__factory_1.OrderRegistrator__factory; } });
var PredicateHelper__factory_1 = require("./factories/contracts/ethereum/official-lop/helpers/PredicateHelper__factory");
Object.defineProperty(exports, "PredicateHelper__factory", { enumerable: true, get: function () { return PredicateHelper__factory_1.PredicateHelper__factory; } });
var SeriesEpochManager__factory_1 = require("./factories/contracts/ethereum/official-lop/helpers/SeriesEpochManager__factory");
Object.defineProperty(exports, "SeriesEpochManager__factory", { enumerable: true, get: function () { return SeriesEpochManager__factory_1.SeriesEpochManager__factory; } });
var SeriesNonceManager__factory_1 = require("./factories/contracts/ethereum/official-lop/helpers/SeriesNonceManager__factory");
Object.defineProperty(exports, "SeriesNonceManager__factory", { enumerable: true, get: function () { return SeriesNonceManager__factory_1.SeriesNonceManager__factory; } });
var IAmountGetter__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/IAmountGetter__factory");
Object.defineProperty(exports, "IAmountGetter__factory", { enumerable: true, get: function () { return IAmountGetter__factory_1.IAmountGetter__factory; } });
var ICreate3Deployer__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/ICreate3Deployer__factory");
Object.defineProperty(exports, "ICreate3Deployer__factory", { enumerable: true, get: function () { return ICreate3Deployer__factory_1.ICreate3Deployer__factory; } });
var IOrderRegistrator__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/IOrderRegistrator__factory");
Object.defineProperty(exports, "IOrderRegistrator__factory", { enumerable: true, get: function () { return IOrderRegistrator__factory_1.IOrderRegistrator__factory; } });
var IPermit2WitnessTransferFrom__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/IPermit2WitnessTransferFrom__factory");
Object.defineProperty(exports, "IPermit2WitnessTransferFrom__factory", { enumerable: true, get: function () { return IPermit2WitnessTransferFrom__factory_1.IPermit2WitnessTransferFrom__factory; } });
var IPostInteraction__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/IPostInteraction__factory");
Object.defineProperty(exports, "IPostInteraction__factory", { enumerable: true, get: function () { return IPostInteraction__factory_1.IPostInteraction__factory; } });
var IPreInteraction__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/IPreInteraction__factory");
Object.defineProperty(exports, "IPreInteraction__factory", { enumerable: true, get: function () { return IPreInteraction__factory_1.IPreInteraction__factory; } });
var ITakerInteraction__factory_1 = require("./factories/contracts/ethereum/official-lop/interfaces/ITakerInteraction__factory");
Object.defineProperty(exports, "ITakerInteraction__factory", { enumerable: true, get: function () { return ITakerInteraction__factory_1.ITakerInteraction__factory; } });
var BitInvalidatorLib__factory_1 = require("./factories/contracts/ethereum/official-lop/libraries/BitInvalidatorLib__factory");
Object.defineProperty(exports, "BitInvalidatorLib__factory", { enumerable: true, get: function () { return BitInvalidatorLib__factory_1.BitInvalidatorLib__factory; } });
var OffsetsLib__factory_1 = require("./factories/contracts/ethereum/official-lop/libraries/OffsetsLib__factory");
Object.defineProperty(exports, "OffsetsLib__factory", { enumerable: true, get: function () { return OffsetsLib__factory_1.OffsetsLib__factory; } });
var RemainingInvalidatorLib__factory_1 = require("./factories/contracts/ethereum/official-lop/libraries/RemainingInvalidatorLib__factory");
Object.defineProperty(exports, "RemainingInvalidatorLib__factory", { enumerable: true, get: function () { return RemainingInvalidatorLib__factory_1.RemainingInvalidatorLib__factory; } });
var LimitOrderProtocol__factory_1 = require("./factories/contracts/ethereum/official-lop/LimitOrderProtocol__factory");
Object.defineProperty(exports, "LimitOrderProtocol__factory", { enumerable: true, get: function () { return LimitOrderProtocol__factory_1.LimitOrderProtocol__factory; } });
var AggregatorMock__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/AggregatorMock__factory");
Object.defineProperty(exports, "AggregatorMock__factory", { enumerable: true, get: function () { return AggregatorMock__factory_1.AggregatorMock__factory; } });
var ArbitraryPredicateMock__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/ArbitraryPredicateMock__factory");
Object.defineProperty(exports, "ArbitraryPredicateMock__factory", { enumerable: true, get: function () { return ArbitraryPredicateMock__factory_1.ArbitraryPredicateMock__factory; } });
var CallsSimulator__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/CallsSimulator__factory");
Object.defineProperty(exports, "CallsSimulator__factory", { enumerable: true, get: function () { return CallsSimulator__factory_1.CallsSimulator__factory; } });
var ExtensionMock__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/ExtensionMock__factory");
Object.defineProperty(exports, "ExtensionMock__factory", { enumerable: true, get: function () { return ExtensionMock__factory_1.ExtensionMock__factory; } });
var HashChecker__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/HashChecker__factory");
Object.defineProperty(exports, "HashChecker__factory", { enumerable: true, get: function () { return HashChecker__factory_1.HashChecker__factory; } });
var InteractionMock__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/InteractionMock__factory");
Object.defineProperty(exports, "InteractionMock__factory", { enumerable: true, get: function () { return InteractionMock__factory_1.InteractionMock__factory; } });
var MakerContract__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/MakerContract__factory");
Object.defineProperty(exports, "MakerContract__factory", { enumerable: true, get: function () { return MakerContract__factory_1.MakerContract__factory; } });
var RecursiveMatcher__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/RecursiveMatcher__factory");
Object.defineProperty(exports, "RecursiveMatcher__factory", { enumerable: true, get: function () { return RecursiveMatcher__factory_1.RecursiveMatcher__factory; } });
var TakerContract__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/TakerContract__factory");
Object.defineProperty(exports, "TakerContract__factory", { enumerable: true, get: function () { return TakerContract__factory_1.TakerContract__factory; } });
var WrappedTokenMock__factory_1 = require("./factories/contracts/ethereum/official-lop/mocks/WrappedTokenMock__factory");
Object.defineProperty(exports, "WrappedTokenMock__factory", { enumerable: true, get: function () { return WrappedTokenMock__factory_1.WrappedTokenMock__factory; } });
var OrderLib__factory_1 = require("./factories/contracts/ethereum/official-lop/OrderLib__factory");
Object.defineProperty(exports, "OrderLib__factory", { enumerable: true, get: function () { return OrderLib__factory_1.OrderLib__factory; } });
var OrderMixin__factory_1 = require("./factories/contracts/ethereum/official-lop/OrderMixin__factory");
Object.defineProperty(exports, "OrderMixin__factory", { enumerable: true, get: function () { return OrderMixin__factory_1.OrderMixin__factory; } });
var Resolver__factory_1 = require("./factories/contracts/ethereum/Resolver__factory");
Object.defineProperty(exports, "Resolver__factory", { enumerable: true, get: function () { return Resolver__factory_1.Resolver__factory; } });
var BaseExtension__factory_1 = require("./factories/contracts/ethereum/temporary-extensions/contracts/extensions/BaseExtension__factory");
Object.defineProperty(exports, "BaseExtension__factory", { enumerable: true, get: function () { return BaseExtension__factory_1.BaseExtension__factory; } });
var ResolverValidationExtension__factory_1 = require("./factories/contracts/ethereum/temporary-extensions/contracts/extensions/ResolverValidationExtension__factory");
Object.defineProperty(exports, "ResolverValidationExtension__factory", { enumerable: true, get: function () { return ResolverValidationExtension__factory_1.ResolverValidationExtension__factory; } });
var TronFusionExtension__factory_1 = require("./factories/contracts/ethereum/TronFusionExtension__factory");
Object.defineProperty(exports, "TronFusionExtension__factory", { enumerable: true, get: function () { return TronFusionExtension__factory_1.TronFusionExtension__factory; } });
var ITronEscrow__factory_1 = require("./factories/contracts/tron/interfaces/ITronEscrow__factory");
Object.defineProperty(exports, "ITronEscrow__factory", { enumerable: true, get: function () { return ITronEscrow__factory_1.ITronEscrow__factory; } });
var AddressLibTest__factory_1 = require("./factories/contracts/tron/test/AddressLibTest__factory");
Object.defineProperty(exports, "AddressLibTest__factory", { enumerable: true, get: function () { return AddressLibTest__factory_1.AddressLibTest__factory; } });
var SimpleImplementation__factory_1 = require("./factories/contracts/tron/test/TronClonesTest.sol/SimpleImplementation__factory");
Object.defineProperty(exports, "SimpleImplementation__factory", { enumerable: true, get: function () { return SimpleImplementation__factory_1.SimpleImplementation__factory; } });
var TronClonesTest__factory_1 = require("./factories/contracts/tron/test/TronClonesTest.sol/TronClonesTest__factory");
Object.defineProperty(exports, "TronClonesTest__factory", { enumerable: true, get: function () { return TronClonesTest__factory_1.TronClonesTest__factory; } });
var TronCreate2Test__factory_1 = require("./factories/contracts/tron/test/TronCreate2Test__factory");
Object.defineProperty(exports, "TronCreate2Test__factory", { enumerable: true, get: function () { return TronCreate2Test__factory_1.TronCreate2Test__factory; } });
var TronEscrowDst__factory_1 = require("./factories/contracts/tron/TronEscrowDst__factory");
Object.defineProperty(exports, "TronEscrowDst__factory", { enumerable: true, get: function () { return TronEscrowDst__factory_1.TronEscrowDst__factory; } });
var TronEscrowFactoryPatched__factory_1 = require("./factories/contracts/tron/TronEscrowFactoryPatched__factory");
Object.defineProperty(exports, "TronEscrowFactoryPatched__factory", { enumerable: true, get: function () { return TronEscrowFactoryPatched__factory_1.TronEscrowFactoryPatched__factory; } });
var TronEscrowSrc__factory_1 = require("./factories/contracts/tron/TronEscrowSrc__factory");
Object.defineProperty(exports, "TronEscrowSrc__factory", { enumerable: true, get: function () { return TronEscrowSrc__factory_1.TronEscrowSrc__factory; } });
//# sourceMappingURL=index.js.map