"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITakerInteraction__factory = exports.IPreInteraction__factory = exports.IPostInteraction__factory = exports.IPermit2WitnessTransferFrom__factory = exports.IOrderRegistrator__factory = exports.IOrderMixin__factory = exports.ICreate3Deployer__factory = exports.IAmountGetter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IAmountGetter__factory_1 = require("./IAmountGetter__factory");
Object.defineProperty(exports, "IAmountGetter__factory", { enumerable: true, get: function () { return IAmountGetter__factory_1.IAmountGetter__factory; } });
var ICreate3Deployer__factory_1 = require("./ICreate3Deployer__factory");
Object.defineProperty(exports, "ICreate3Deployer__factory", { enumerable: true, get: function () { return ICreate3Deployer__factory_1.ICreate3Deployer__factory; } });
var IOrderMixin__factory_1 = require("./IOrderMixin__factory");
Object.defineProperty(exports, "IOrderMixin__factory", { enumerable: true, get: function () { return IOrderMixin__factory_1.IOrderMixin__factory; } });
var IOrderRegistrator__factory_1 = require("./IOrderRegistrator__factory");
Object.defineProperty(exports, "IOrderRegistrator__factory", { enumerable: true, get: function () { return IOrderRegistrator__factory_1.IOrderRegistrator__factory; } });
var IPermit2WitnessTransferFrom__factory_1 = require("./IPermit2WitnessTransferFrom__factory");
Object.defineProperty(exports, "IPermit2WitnessTransferFrom__factory", { enumerable: true, get: function () { return IPermit2WitnessTransferFrom__factory_1.IPermit2WitnessTransferFrom__factory; } });
var IPostInteraction__factory_1 = require("./IPostInteraction__factory");
Object.defineProperty(exports, "IPostInteraction__factory", { enumerable: true, get: function () { return IPostInteraction__factory_1.IPostInteraction__factory; } });
var IPreInteraction__factory_1 = require("./IPreInteraction__factory");
Object.defineProperty(exports, "IPreInteraction__factory", { enumerable: true, get: function () { return IPreInteraction__factory_1.IPreInteraction__factory; } });
var ITakerInteraction__factory_1 = require("./ITakerInteraction__factory");
Object.defineProperty(exports, "ITakerInteraction__factory", { enumerable: true, get: function () { return ITakerInteraction__factory_1.ITakerInteraction__factory; } });
//# sourceMappingURL=index.js.map