"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITronEscrow__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ITronEscrow__factory_1 = require("./ITronEscrow__factory");
Object.defineProperty(exports, "ITronEscrow__factory", { enumerable: true, get: function () { return ITronEscrow__factory_1.ITronEscrow__factory; } });
//# sourceMappingURL=index.js.map