"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TronFusionExtension__factory = exports.Resolver__factory = exports.MockTRX__factory = exports.DemoResolverV2__factory = exports.DemoResolver__factory = exports.temporaryExtensions = exports.officialLop = exports.officialEscrow = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.officialEscrow = __importStar(require("./official-escrow"));
exports.officialLop = __importStar(require("./official-lop"));
exports.temporaryExtensions = __importStar(require("./temporary-extensions"));
var DemoResolver__factory_1 = require("./DemoResolver__factory");
Object.defineProperty(exports, "DemoResolver__factory", { enumerable: true, get: function () { return DemoResolver__factory_1.DemoResolver__factory; } });
var DemoResolverV2__factory_1 = require("./DemoResolverV2__factory");
Object.defineProperty(exports, "DemoResolverV2__factory", { enumerable: true, get: function () { return DemoResolverV2__factory_1.DemoResolverV2__factory; } });
var MockTRX__factory_1 = require("./MockTRX__factory");
Object.defineProperty(exports, "MockTRX__factory", { enumerable: true, get: function () { return MockTRX__factory_1.MockTRX__factory; } });
var Resolver__factory_1 = require("./Resolver__factory");
Object.defineProperty(exports, "Resolver__factory", { enumerable: true, get: function () { return Resolver__factory_1.Resolver__factory; } });
var TronFusionExtension__factory_1 = require("./TronFusionExtension__factory");
Object.defineProperty(exports, "TronFusionExtension__factory", { enumerable: true, get: function () { return TronFusionExtension__factory_1.TronFusionExtension__factory; } });
//# sourceMappingURL=index.js.map