"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BitInvalidatorLib__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "BitInvalidatedOrder",
        type: "error",
    },
];
const _bytecode = "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220443dd77b30dbb404a915aafda51a434dcd177cdeddb3e410aa069b11e41f4fc064736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class BitInvalidatorLib__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.BitInvalidatorLib__factory = BitInvalidatorLib__factory;
BitInvalidatorLib__factory.bytecode = _bytecode;
BitInvalidatorLib__factory.abi = _abi;
//# sourceMappingURL=BitInvalidatorLib__factory.js.map