"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OffsetsLib__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "OffsetOutOfBounds",
        type: "error",
    },
];
const _bytecode = "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220346d2ffb03999d2a02bfb8ba1e3aab685ed7afaece920368d782353e93dac8f964736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class OffsetsLib__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.OffsetsLib__factory = OffsetsLib__factory;
OffsetsLib__factory.bytecode = _bytecode;
OffsetsLib__factory.abi = _abi;
//# sourceMappingURL=OffsetsLib__factory.js.map