"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RemainingInvalidatorLib__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "RemainingInvalidatedOrder",
        type: "error",
    },
];
const _bytecode = "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212201bcbb3de21342a934c0b339b4571332c1cb15756f8bb938c5a2abbeffea6ee3164736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class RemainingInvalidatorLib__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.RemainingInvalidatorLib__factory = RemainingInvalidatorLib__factory;
RemainingInvalidatorLib__factory.bytecode = _bytecode;
RemainingInvalidatorLib__factory.abi = _abi;
//# sourceMappingURL=RemainingInvalidatorLib__factory.js.map