"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MinimalProxyZkSync__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "implementation",
                type: "address",
            },
        ],
        stateMutability: "payable",
        type: "constructor",
    },
    {
        stateMutability: "payable",
        type: "fallback",
    },
];
const _bytecode = "0x60a0601f6100f638819003918201601f19168301916001600160401b038311848410176100685780849260209460405283398101031261006357516001600160a01b0381168103610063576080526040516077908161007f82396080518160100152f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe6080604052600036818037808036817f00000000000000000000000000000000000000000000000000000000000000005af43d82803e15603d573d90f35b3d90fdfea264697066735822122055c87c8fe4745171c04a045085faa48412430cb819aa66ceae43fdb00bb0c21764736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class MinimalProxyZkSync__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(implementation, overrides) {
        return super.getDeployTransaction(implementation, overrides || {});
    }
    deploy(implementation, overrides) {
        return super.deploy(implementation, overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.MinimalProxyZkSync__factory = MinimalProxyZkSync__factory;
MinimalProxyZkSync__factory.bytecode = _bytecode;
MinimalProxyZkSync__factory.abi = _abi;
//# sourceMappingURL=MinimalProxyZkSync__factory.js.map