"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.RangeAmountCalculator__factory = exports.Permit2WitnessProxy__factory = exports.OrderIdInvalidator__factory = exports.ImmutableOwner__factory = exports.FeeTaker__factory = exports.ETHOrders__factory = exports.ERC721ProxySafe__factory = exports.ERC721Proxy__factory = exports.ERC1155Proxy__factory = exports.DutchAuctionCalculator__factory = exports.ChainlinkCalculator__factory = exports.ApprovalPreInteraction__factory = exports.AmountGetterWithFee__factory = exports.AmountGetterBase__factory = exports.prioirityFeeLimiterSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.prioirityFeeLimiterSol = __importStar(require("./PrioirityFeeLimiter.sol"));
var AmountGetterBase__factory_1 = require("./AmountGetterBase__factory");
Object.defineProperty(exports, "AmountGetterBase__factory", { enumerable: true, get: function () { return AmountGetterBase__factory_1.AmountGetterBase__factory; } });
var AmountGetterWithFee__factory_1 = require("./AmountGetterWithFee__factory");
Object.defineProperty(exports, "AmountGetterWithFee__factory", { enumerable: true, get: function () { return AmountGetterWithFee__factory_1.AmountGetterWithFee__factory; } });
var ApprovalPreInteraction__factory_1 = require("./ApprovalPreInteraction__factory");
Object.defineProperty(exports, "ApprovalPreInteraction__factory", { enumerable: true, get: function () { return ApprovalPreInteraction__factory_1.ApprovalPreInteraction__factory; } });
var ChainlinkCalculator__factory_1 = require("./ChainlinkCalculator__factory");
Object.defineProperty(exports, "ChainlinkCalculator__factory", { enumerable: true, get: function () { return ChainlinkCalculator__factory_1.ChainlinkCalculator__factory; } });
var DutchAuctionCalculator__factory_1 = require("./DutchAuctionCalculator__factory");
Object.defineProperty(exports, "DutchAuctionCalculator__factory", { enumerable: true, get: function () { return DutchAuctionCalculator__factory_1.DutchAuctionCalculator__factory; } });
var ERC1155Proxy__factory_1 = require("./ERC1155Proxy__factory");
Object.defineProperty(exports, "ERC1155Proxy__factory", { enumerable: true, get: function () { return ERC1155Proxy__factory_1.ERC1155Proxy__factory; } });
var ERC721Proxy__factory_1 = require("./ERC721Proxy__factory");
Object.defineProperty(exports, "ERC721Proxy__factory", { enumerable: true, get: function () { return ERC721Proxy__factory_1.ERC721Proxy__factory; } });
var ERC721ProxySafe__factory_1 = require("./ERC721ProxySafe__factory");
Object.defineProperty(exports, "ERC721ProxySafe__factory", { enumerable: true, get: function () { return ERC721ProxySafe__factory_1.ERC721ProxySafe__factory; } });
var ETHOrders__factory_1 = require("./ETHOrders__factory");
Object.defineProperty(exports, "ETHOrders__factory", { enumerable: true, get: function () { return ETHOrders__factory_1.ETHOrders__factory; } });
var FeeTaker__factory_1 = require("./FeeTaker__factory");
Object.defineProperty(exports, "FeeTaker__factory", { enumerable: true, get: function () { return FeeTaker__factory_1.FeeTaker__factory; } });
var ImmutableOwner__factory_1 = require("./ImmutableOwner__factory");
Object.defineProperty(exports, "ImmutableOwner__factory", { enumerable: true, get: function () { return ImmutableOwner__factory_1.ImmutableOwner__factory; } });
var OrderIdInvalidator__factory_1 = require("./OrderIdInvalidator__factory");
Object.defineProperty(exports, "OrderIdInvalidator__factory", { enumerable: true, get: function () { return OrderIdInvalidator__factory_1.OrderIdInvalidator__factory; } });
var Permit2WitnessProxy__factory_1 = require("./Permit2WitnessProxy__factory");
Object.defineProperty(exports, "Permit2WitnessProxy__factory", { enumerable: true, get: function () { return Permit2WitnessProxy__factory_1.Permit2WitnessProxy__factory; } });
var RangeAmountCalculator__factory_1 = require("./RangeAmountCalculator__factory");
Object.defineProperty(exports, "RangeAmountCalculator__factory", { enumerable: true, get: function () { return RangeAmountCalculator__factory_1.RangeAmountCalculator__factory; } });
//# sourceMappingURL=index.js.map