/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tronClonesTestSol from "./TronClonesTest.sol";
export { AddressLibTest__factory } from "./AddressLibTest__factory";
export { TronCreate2Test__factory } from "./TronCreate2Test__factory";
