"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PriorityFeeLimiter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "isPriorityFeeValid",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
const _bytecode = "0x608080604052346100155760c0908161001b8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c630202470814602857600080fd5b3460455781600319360112604557602090603f6049565b15158152f35b5080fd5b483a03640277cf2a0048106000146067576064604648029102111590565b64183cd7f100481015607d57489060011b111590565b606460414802910211159056fea26469706673582212206e92816baae7f51af40aedf413dee454a5ea8c0bd82000197a9c57f3634158ef64736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class PriorityFeeLimiter__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.PriorityFeeLimiter__factory = PriorityFeeLimiter__factory;
PriorityFeeLimiter__factory.bytecode = _bytecode;
PriorityFeeLimiter__factory.abi = _abi;
//# sourceMappingURL=PriorityFeeLimiter__factory.js.map