"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleImplementation__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "getValue",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
            },
        ],
        name: "setValue",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "value",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        stateMutability: "payable",
        type: "receive",
    },
];
const _bytecode = "0x608080604052346100155760c9908161001b8239f35b600080fdfe6080806040526004361015601b575b503615601957600080fd5b005b600090813560e01c90816320965255146077575080633fa4f24514605c57635524107703600e57346059576020366003190112605957600435815580f35b80fd5b50346059578060031936011260595760209054604051908152f35b905034608f5781600319360112608f57602091548152f35b5080fdfea2646970667358221220e2220cf52f255a287214c35f533aa8b81a6900a532cfa2a0357bcaf546abd04464736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class SimpleImplementation__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.SimpleImplementation__factory = SimpleImplementation__factory;
SimpleImplementation__factory.bytecode = _bytecode;
SimpleImplementation__factory.abi = _abi;
//# sourceMappingURL=SimpleImplementation__factory.js.map