/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseExtension } from "./BaseExtension";
export type { ResolverValidationExtension } from "./ResolverValidationExtension";
