/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { TronEscrowDst } from "./TronEscrowDst";
export type { TronEscrowFactory } from "./TronEscrowFactory";
export type { TronEscrowSrc } from "./TronEscrowSrc";
