/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { TronEscrowDst } from "./TronEscrowDst";
export type { TronEscrowFactoryPatched } from "./TronEscrowFactoryPatched";
export type { TronEscrowSrc } from "./TronEscrowSrc";
