"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC1155__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC1155__factory_1 = require("./IERC1155__factory");
Object.defineProperty(exports, "IERC1155__factory", { enumerable: true, get: function () { return IERC1155__factory_1.IERC1155__factory; } });
//# sourceMappingURL=index.js.map