"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SeriesEpochManager__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "AdvanceEpochFailed",
        type: "error",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "maker",
                type: "address",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "series",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "newEpoch",
                type: "uint256",
            },
        ],
        name: "EpochIncreased",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint96",
                name: "series",
                type: "uint96",
            },
            {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "advanceEpoch",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "maker",
                type: "address",
            },
            {
                internalType: "uint96",
                name: "series",
                type: "uint96",
            },
        ],
        name: "epoch",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "maker",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "series",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "makerEpoch",
                type: "uint256",
            },
        ],
        name: "epochEquals",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint96",
                name: "series",
                type: "uint96",
            },
        ],
        name: "increaseEpoch",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x608080604052346100165761027b908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c9081630d2c7c161461016b57508063c3cf8043146100f3578063ce3d710a146100b05763fcea9e4e1461004e57600080fd5b346100ac57806003193601126100ac5761006661022f565b6024356001600160601b03811681036100a8576001600160a01b0390911660a09190911b6001600160a01b031916178252602082815291819020549051908152f35b8380fd5b5080fd5b50346100ac5760603660031901126100ac576020916100cd61022f565b6001600160a01b031660243560a01b178152808352819020549051604435919091148152f35b50346100ac5760203660031901126100ac577f099133aefc2c2d1e56f8ef3622ec8e80979a0713fc9c4e1497740efcf809939661012e610214565b916001600160601b0360a01b8360a01b16331784528360205280842060018154018091556001600160601b0382519416845260208401523392a280f35b91905034610210578060031936011261021057610186610214565b916024359081158015610206575b6101f75750907f099133aefc2c2d1e56f8ef3622ec8e80979a0713fc9c4e1497740efcf8099396916001600160601b0360a01b8460a01b163317855284602052818520908154018091556001600160601b0382519416845260208401523392a280f35b63555fbbbf60e01b8152600490fd5b5060ff8211610194565b8280fd5b600435906001600160601b038216820361022a57565b600080fd5b600435906001600160a01b038216820361022a5756fea26469706673582212204e8d28d0bede4a65c658d2c403fe6b688e9dec595afd9c76c6948f70694d6fbf64736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class SeriesEpochManager__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.SeriesEpochManager__factory = SeriesEpochManager__factory;
SeriesEpochManager__factory.bytecode = _bytecode;
SeriesEpochManager__factory.abi = _abi;
//# sourceMappingURL=SeriesEpochManager__factory.js.map