/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleImplementation } from "./SimpleImplementation";
export type { TronClonesTest } from "./TronClonesTest";
