"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResolverValidationExtension__factory = exports.BaseExtension__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BaseExtension__factory_1 = require("./BaseExtension__factory");
Object.defineProperty(exports, "BaseExtension__factory", { enumerable: true, get: function () { return BaseExtension__factory_1.BaseExtension__factory; } });
var ResolverValidationExtension__factory_1 = require("./ResolverValidationExtension__factory");
Object.defineProperty(exports, "ResolverValidationExtension__factory", { enumerable: true, get: function () { return ResolverValidationExtension__factory_1.ResolverValidationExtension__factory; } });
//# sourceMappingURL=index.js.map