/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tronClonesTestSol from "./TronClonesTest.sol";
export type { tronClonesTestSol };
export type { AddressLibTest } from "./AddressLibTest";
export type { TronCreate2Test } from "./TronCreate2Test";
