"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderMixin__factory = exports.OrderLib__factory = exports.LimitOrderProtocol__factory = exports.mocks = exports.libraries = exports.interfaces = exports.helpers = exports.extensions = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.extensions = __importStar(require("./extensions"));
exports.helpers = __importStar(require("./helpers"));
exports.interfaces = __importStar(require("./interfaces"));
exports.libraries = __importStar(require("./libraries"));
exports.mocks = __importStar(require("./mocks"));
var LimitOrderProtocol__factory_1 = require("./LimitOrderProtocol__factory");
Object.defineProperty(exports, "LimitOrderProtocol__factory", { enumerable: true, get: function () { return LimitOrderProtocol__factory_1.LimitOrderProtocol__factory; } });
var OrderLib__factory_1 = require("./OrderLib__factory");
Object.defineProperty(exports, "OrderLib__factory", { enumerable: true, get: function () { return OrderLib__factory_1.OrderLib__factory; } });
var OrderMixin__factory_1 = require("./OrderMixin__factory");
Object.defineProperty(exports, "OrderMixin__factory", { enumerable: true, get: function () { return OrderMixin__factory_1.OrderMixin__factory; } });
//# sourceMappingURL=index.js.map