"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMerkleStorageInvalidator__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "AccessDenied",
        type: "error",
    },
    {
        inputs: [],
        name: "InvalidProof",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "key",
                type: "bytes32",
            },
        ],
        name: "lastValidated",
        outputs: [
            {
                internalType: "uint256",
                name: "index",
                type: "uint256",
            },
            {
                internalType: "bytes32",
                name: "secretHash",
                type: "bytes32",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IMerkleStorageInvalidator__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.IMerkleStorageInvalidator__factory = IMerkleStorageInvalidator__factory;
IMerkleStorageInvalidator__factory.abi = _abi;
//# sourceMappingURL=IMerkleStorageInvalidator__factory.js.map