"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UniERC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "ApproveCalledOnETH",
        type: "error",
    },
    {
        inputs: [],
        name: "ETHTransferFailed",
        type: "error",
    },
    {
        inputs: [],
        name: "FromIsNotSender",
        type: "error",
    },
    {
        inputs: [],
        name: "InsufficientBalance",
        type: "error",
    },
    {
        inputs: [],
        name: "NotEnoughValue",
        type: "error",
    },
    {
        inputs: [],
        name: "ToIsNotThis",
        type: "error",
    },
];
const _bytecode = "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212204dbce5e09b7a6617d01ee82ddbf339c5475a3d9913ef2deb85d2068c70719ae864736f6c63430008170033";
const isSuperArgs = (xs) => xs.length > 1;
class UniERC20__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.UniERC20__factory = UniERC20__factory;
UniERC20__factory.bytecode = _bytecode;
UniERC20__factory.abi = _abi;
//# sourceMappingURL=UniERC20__factory.js.map